version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "npm"
    directory: "/src/main/frontend"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
