# Assumptions:
# 1. Runner has installed:
#     - Java 21
#     - Node 20.x.x

name: Deploy app

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.3

      - name: Build backend jar
        run: mvn package -Dmaven.test.skip=true -B -U -ntp

      - name: Install Front-end dependencies
        run: npm ci
        working-directory: ./src/main/frontend

      - name: Build Front-end
        run: npm run build
        working-directory: ./src/main/frontend