# Assumptions:
# 1. Runner has installed:
#     - Java 21

name: Deploy app

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Maven ${{ vars.MAVENVERSION }}
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: ${{ vars.MAVENVERSION }}

      - name: Set up Node.js ${{ vars.NODEVERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODEVERSION }}

      - name: Build backend jar
        run: mvn package --batch-mode -Dmaven.test.skip=true --no-transfer-progress --update-snapshots

      - name: Install Front-end dependencies
        run: npm ci --no-fund
        working-directory: ./src/main/frontend

      - name: Build Front-end
        run: npm run build
        working-directory: ./src/main/frontend