name: CI/CD

on: push

jobs:
  verify:
    name: Back-end verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Maven verify
        run: mvn verify --no-transfer-progress --update-snapshots

  buildFront:
    name: Front-end verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ vars.NODEVERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODEVERSION }}

      - name: Install dependencies
        run: npm ci --no-fund
        working-directory: ./src/main/frontend

      - name: Build
        run: npm run build
        working-directory: ./src/main/frontend

  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}